package com.w3schools.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-09-22T16:08:02.055+03:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://www.w3schools.com/webservices/", name = "TempConvertHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TempConvertHttpPost {

    @WebMethod(operationName = "CelsiusToFahrenheit")
    @WebResult(name = "string", targetNamespace = "http://www.w3schools.com/webservices/", partName = "Body")
    public java.lang.String celsiusToFahrenheit(
        @WebParam(partName = "Celsius", name = "Celsius", targetNamespace = "http://www.w3schools.com/webservices/")
        java.lang.String celsius
    );

    @WebMethod(operationName = "FahrenheitToCelsius")
    @WebResult(name = "string", targetNamespace = "http://www.w3schools.com/webservices/", partName = "Body")
    public java.lang.String fahrenheitToCelsius(
        @WebParam(partName = "Fahrenheit", name = "Fahrenheit", targetNamespace = "http://www.w3schools.com/webservices/")
        java.lang.String fahrenheit
    );
}
